name: Build cache archive

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout marketplace backend
        uses: actions/checkout@v3
        with:
          repository: "onlydustxyz/marketplace-backend"
          path: "marketplace-backend"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63
          components: ${{ inputs.components }}
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            marketplace-backend/target/
          key: ${{ runner.os }}-cargo-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ inputs.key }}-
            ${{ runner.os }}-cargo-

      - name: Compile marketplace backend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path marketplace-backend/Cargo.toml --release

      - name: Archive the target directory
        run: tar -czf target.tar.gz -C ./marketplace-backend target

      - name: Upload the archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: target.tar.gz
          path: target.tar.gz
